sin_miedo_al_exito/core/urls.py
from django.urls import path
from . import views

app_name="core"

urlpatterns = [
    path("", views.index.as_view(), name='index'),
    path("acerca_de/", views.acerca_de.as_view(), name='acerca_de'),
    path("raul/", views.raul.as_view(), name='portafolio_raul'),
    path("martin/", views.martin.as_view(), name='portafolio_martin'),
    path("contactanos/", views.contactanos.as_view(), name='contactanos'),
]

sin_miedo_al_exito/cursos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name="cursos"

urlpatterns = [
    path('listado_de_cursos/',views.cursoListView.as_view(), name='listado_cursos' ),
    path('<int:pk>/', views.cursoDetailView.as_view(), name='curso_detalle'),
    path('crear_curso/', login_required(views.cursoCreate.as_view()), name='curso_crear'),
    path('actualizar_curso/<int:pk>/', login_required(views.cursoUpdate.as_view()), name='actualizar_curso'),
    path('borrar_curso/<int:pk>/', login_required(views.cursoDelete.as_view()), name='borrar_curso'),
]

sin_miedo_al_exito/sin_miedo_al_exito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace='core')),
    path('', include("cursos.urls", namespace='course')),
    path('', include("usuarios.urls", namespace='usuarios')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sin_miedo_al_exito/usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, logout_then_login
from django.views.generic import TemplateView

app_name = "usuarios"

urlpatterns = [
    path('accounts/login/',LoginView.as_view(template_name= 'usuarios/login.html'), name='inicio_sesion'),
    path('logout/',logout_then_login, name='cerrar_sesion' )
]

sin_miedo_al_exito/core/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class versiones_python(models.Model):
    nombre = models.CharField(max_length=80, verbose_name="Nombre")
    descripcion = models.TextField(verbose_name="Descripcion")
    imagenes = models.ImageField(verbose_name="Imagen", upload_to="imagenes_versiones")
    url = models.URLField(verbose_name="Link Referencia", max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Meta:
    verbose_name = "Version"
    verbose_name_plural = "Versiones"
    ordering = ["created"]


def __str__(self):
    return self.nombre

class mensaje(models.Model):
    nombre = models.CharField(max_length=75, verbose_name="Nombre")
    apellido = models.CharField(max_length=75, verbose_name="Apellido")
    domicilio = models.CharField(max_length=100, verbose_name="Domicilio")
    ciudad = models.CharField(max_length=75, verbose_name="Ciudad")
    pais = models.CharField(max_length=10, verbose_name="PaÍs")
    codigo_postal = models.CharField(max_length=50, verbose_name="Codigo Postal")
    email= models.EmailField(max_length=150, verbose_name="Email")
    num_telefono = models.CharField(max_length=75, verbose_name="Numero de Telefono")
    msj = models.TextField(verbose_name="Mensaje")

    def get_absolute_url(self):
        return reverse('curso_detail')

    class Meta:
        verbose_name = "Mensaje"
        verbose_name_plural = "Mensajes"
    
    def __str__(self):
        return self.nombre

sin_miedo_al_exito/core/forms.py
from django import forms
from .models import mensaje

class mensajeForm(forms.ModelForm):

    class Meta:
        model = mensaje
        fields = [
                    'nombre',
                    'apellido',
                    'domicilio',
                    'ciudad',
                    'pais',
                    'codigo_postal',
                    'email',
                    'num_telefono',
                    'msj'
                ]

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control','placeholder':'Título'}),
            'apellido': forms.TextInput(attrs={'class':'form-control','placeholder':'Apellido'}),
            'domicilio': forms.TextInput(attrs={'class':'form-control','placeholder':'Domicilio'}),
            'ciudad': forms.TextInput(attrs={'class':'form-control','placeholder':'Domicilio'}),
            'codigo_postal': forms.TextInput(attrs={'class':'form-control','placeholder':'Codigo Postal'}),
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
            'num_telefono': forms.TextInput(attrs={'class':'for-control','placeholder':'Numero de Telefono'}),
            'msj': forms.Textarea(attrs={'class':'form-control','placeholder':'mensaje'})
        }

        labels = {
                    'nombre':'Nombre:',
                    'apellido':'Apellido:',
                    'domicilio':'Domicilio:',
                    'ciudad':'Ciudad:',
                    'pais':'País:',
                    'codigo_postal':'Codigo Postal:',
                    'email':'Email:',
                    'num_telefono':'Número de Telefono (Celular)',
                    'msj':'Mensaje'
            }

sin_miedo_al_exito/core/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.edit import CreateView
from django.urls import reverse, reverse_lazy
from .models import versiones_python, mensaje
from .forms import mensajeForm
# Create your views here.

class index(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, "core/index.html", context)

class acerca_de(View):
    def get(self, request, *args, **kwargs):
        list_vers_python = versiones_python.objects.all()
        context = {
            'listado_versiones': list_vers_python
        }
        return render(request, "core/acercade.html", context)

class raul(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, "core/raul.html", context)   

class martin(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'core/portfolio_martin.html', context)

class contactanos(CreateView):
    model = mensaje
    form_class = mensajeForm
    success_url = reverse_lazy('core:acerca_de')

sin_miedo_al_exito/core/templates/core/acercade.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Acerca De{%endblock title %}
{% block estilos %}{% static 'css/estilos.css' %}{% endblock estilos %}
{% block nav_inicio %}{% url 'core:index' %}{% endblock nav_inicio %}
{% block nav_acerca_de %}#{% endblock nav_acerca_de %}
{% block contactanos %}{% url 'core:contactanos' %}{% endblock contactanos %}
{% block content %}
<div class="container contenedor">
    <div class="row">
        <div class="col-12 col-md-5 row">
            <div class="col-12">
                <h2 class="video_tema texto_titulo p-5">HISTORIA DE PYTHON</h2>
            </div>
            <div class="col-12">
                <p class="col-12 texto_parrafo p-2">Un video corto con un resumen de la historia de <strong>PYTHON</strong> hecho por el creador de contenido <strong>CODIGO FACILITO</strong></p>
            </div>
        </div>
        <div class="col-12 col-md-7 d-flex justify-content-center">
            <iframe class="ratio ratio-21x9" src="https://www.youtube.com/embed/KGivghDWg_c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div class="container contenedor p-2">
    <div class="col-12 row">
        <div class="col">
            <h2 class="texto_titulo p-5">VERSIONES DE PYTHON</h2>
        </div>
        <div class="col">
            <p class="texto_parrafo p-2">Al igual que toda herramienta de la que hacemos uso en el hambito de la programacion <strong>PYTHON</strong> ha pasado por varias versiones. A continuacion vamos a listar muchas de ellas.</p>
        </div>
    </div>
    <ul class="list-group" scrolling="auto">
    {% for version_python in listado_versiones %}
        <li class="list-group-item zoom fondo_items">
        <div class="row">
            <div class="row col-12 col-md-7">
                <div class="col-12">
                    <h3 class="titulo_version">{{version_python.nombre}}</h3>
                </div>
                <div class="col-12">
                    <p class="descripcion_version">{{version_python.descripcion}}</p>
                </div>
            </div>
            <div class="col-12 col-md-5">
                <a class="link_version" target="_blank" href="{{version_python.url}}">
                    <img class="w-75 zoom_img_ver rounded mx-auto d-block" src="{{version_python.imagenes.url}}" alt="imagen version">
                </a>
            </div>
        </div>
        </li>
    {% endfor %}
    </ul>
</div>

<!--raul-->
<div class="container mt-3">
    <center>
        <p class="fw-bold text-decoration-underline fs-1">Editores de Código de Python o entornos de desarrollo IDE</p>
    </center>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3"
                aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4"
                aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5"
                aria-label="Slide 6"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="6"
                aria-label="Slide 7"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="7"
                aria-label="Slide 8"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="8"
                aria-label="Slide 9"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="9"
                aria-label="Slide 10"></button>
        </div>

        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/ide4.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://www.sublimetext.com/" target="_blank" rel="noopener noreferrer">Sublime Text
                            3</a></h5>
                    <p>Sublime Text 3 es un editor de código que admite muchos idiomas, incluido Python. Tiene soporte básico incorporado para Python. La personalización de Sublime Text 3 está disponible para crear un entorno de programación Python completo. El editor es compatible con los sistemas operativos OS X, Windows y Linux.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide2.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://www.spyder-ide.org/" target="_blank" rel="noopener noreferrer">Spyder</a></h5>
                    <p>Spyder es un entorno de desarrollo científico integrado escrito en Python. Este software está diseñado para y por científicos que pueden integrarse con Matplotlib, SciPy, NumPy, Pandas, Cython, IPython, SymPy y otro software de código abierto. </p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide3.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://docs.python.org/3/library/idle.html" target="_blank"
                            rel="noopener noreferrer">IDLE</a></h5>
                            <p>IDLE (Integrated Development and Learning Environment) es un editor predeterminado que viene con Python. Este software ayuda a un principiante a aprender Python fácilmente. El paquete de software IDLE es opcional para muchas distribuciones de Linux. La herramienta se puede usar en Windows, macOS y Unix.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide1.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://www.jetbrains.com/pycharm/" target="_blank"
                            rel="noopener noreferrer">PyCharm</a></h5>
                    <p>PyCharm es un IDE multiplataforma utilizado para la programación de Python. Este editor se puede usar en Windows, macOS y Linux. Este software contiene API que los desarrolladores pueden usar para escribir sus propios complementos de Python para que puedan ampliar las funcionalidades básicas. Además, es un editor gratuito; además de ofrecer una versión de pago.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide5.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://code.visualstudio.com/" target="_blank" rel="noopener noreferrer">Visual Studio
                            Code</a></h5>
                    <p>Visual Studio Code (VS Code) es un entorno de código abierto desarrollado por Microsoft. Este IDE se puede usar para el desarrollo de Python. Visual Studio Code se basa en Electron, que es un marco para implementar aplicaciones Node JS para la computadora que se ejecuta en el motor del navegador Blink.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide6.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://atom.io/" target="_blank" rel="noopener noreferrer">Atom</a></h5>
                    <p>Atom es una herramienta útil de editor de código preferida por los programadores debido a su interfaz simple en comparación con los otros editores. Los usuarios de Atom pueden enviar paquetes y ellos para el software.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide7.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://jupyter.org/install.html" target="_blank" rel="noopener noreferrer">Jupyter</a>
                    </h5>
                    <p>Jupyter es una herramienta para las personas que acaban de comenzar con la ciencia de datos. Es un IDE interactivo de ciencia de datos fácil de usar en muchos lenguajes de programación.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide8.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://www.pydev.org/" target="_blank" rel="noopener noreferrer">Pydev</a></h5>
                    <p>PyDev es un editor de Python de terceros para Eclipse. Este editor puede usarse no solo en Python sino también en el desarrollo de IronPython y Jython.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide9.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://wingware.com/" target="_blank" rel="noopener noreferrer">Wing</a></h5>
                    <p>Wing es un entorno ligero de Python diseñado para brindarle una experiencia de desarrollo productiva. Precio: la prueba Wing Pro es gratuita. Wind Personal y Wing 101 son versiones pagas.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ide10.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a style="text-decoration: none; color: rgb(7, 216, 146);" href="https://www.activestate.com/products/komodo-ide/" target="_blank"
                            rel="noopener noreferrer">Komodo Active Python</a></h5>
                    <p class="text-dark">Aumenta la productividad en el desarrollo de software relacionado a la ciencia de datos con una distribución de Python segura y compatible.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
{% endblock content %}

sin_miedo_al_exito/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S_M_A_E - {% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'images/logo_pagina_django.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% block estilos %}{% endblock estilos %}">
</head>
<body>
    <div class="preloader">
        <div class="spiner1">
            <div class="spiner2">
                <div class="spiner3">
                    <div class="spiner4">
                        <div class="spiner5"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <header>
        <nav class="navbar navbar-expand-xl p-0">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% block nav_inicio %}{% endblock nav_inicio %}">
                    <img class="logo_encabezado zoom_img" src="{% static 'images/logo_encabezado_pagina_django.png' %}" alt="logo_grupo" width="100rem">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <div>    
                                <a class="nav-link btn btn-one" href="{% block nav_acerca_de %}{% endblock nav_acerca_de %}"><font size="5">Acerca De</font></a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div>                               
                                <a class="nav-link btn btn-one" href="{% url 'cursos:listado_cursos' %}"><font size="5">Cursos</font></a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div>                               
                                <a class="nav-link btn btn-one" href="{% block contactanos %}{% endblock contactanos %}"><font size="5">Contactanos</font></a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle btn btn-one" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><font size="5">Usuarios</font></a>
                            <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <div class="contenedor-botones">
                                        <a class="nav-link btn btn-one botones" href="{% url 'usuarios:inicio_sesion' %}">Iniciar Sesión</a>
                                    </div>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li class="nav-item">
                                    <div class="contenedor-botones">
                                        <a class="nav-link btn btn-one botones" href="{% url 'usuarios:cerrar_sesion' %}">Cerrar Sesión</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li>
                            {% block busqueda %}{% endblock busqueda %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">
        <div class="row p-5">
            <h1 class="col titulo-paginas">
                <span class="primera letra_titulo">S</span>
                <span class="segunda letra_titulo">i</span>
                <span class="tercera letra_titulo">n</span>
                <span class="letra_titulo"> </span>
                <span class="cuarta letra_titulo">M</span>
                <span class="quinta letra_titulo">i</span>
                <span class="sexta letra_titulo">e</span>
                <span class="septima letra_titulo">d</span>
                <span class="octaba letra_titulo">o</span>
                <span class="letra_titulo"> </span>
                <span class="novena letra_titulo">a</span>
                <span class="decima letra_titulo">l</span>
                <span class="letra_titulo"> </span>
                <span class="decimo_primera letra_titulo">E</span>
                <span class="decimo_segunda letra_titulo">x</span>
                <span class="decimo_tercera letra_titulo">i</span>
                <span class="decimo_cuarta letra_titulo">t</span>
                <span class="decimo_quinta letra_titulo">o</span>
            </h1>
        </div>
    {% block content %}
    {% endblock content %}
    </main>
    <footer>
        <center>        
            <h2 class="p-5 titulo_footer">INTEGRANTES DEL GRUPO</h2>
        </center>
        <div class="row">
            <div class="col-12 col-lg-6 d-flex justify-content-center">
                <div class="card contenedor">
                    <div class="row">
                        <div class="col-12 col-md-6 text-center">
                            <img class="w-100 p-3" src="{% static 'images/imagen_perfil_Raul_Alberto_Suarez.png' %}" class="card-img-top" alt="...">
                        </div>
                        <div class="row col-12 col-md-6 text-center">
                            <div class="col-12">
                                <h3 class="titulo_footer_card p-3">Raul Suarez</h3>
                                <div class=" p-3">
                                    <a class="btn btn-one text-light" target="_blank" href="{% url 'core:portafolio_raul' %}">Sobre Mi</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 d-flex justify-content-center">
                <div class="card contenedor">
                    <div class="row">
                        <div class="col-12 col-md-6 text-center">
                            <img class="w-100 p-3" src="{% static 'images/imagen_perfil_Vilca_Martin_Carlos_Domingo.png' %}" class="card-img-top" alt="...">
                        </div>
                        <div class="row col-12 col-md-6 text-center">
                            <div class="col-12">
                                <h3 class="titulo_footer_card p-3">Martin Vilca</h3>
                                <div class=" p-3">
                                    <a class="btn btn-one text-light" target="_blank" href="{% url 'core:portafolio_martin' %}">Sobre Mi</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/preloader.js' %}"></script>
</body>
</html>

sin_miedo_al_exito/core/templates/core/mensaje_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Contactanos{% endblock title %}
{% block estilos %}{% static 'css/estilos.css' %}{% endblock estilos %}
{% block nav_inicio %}{% url 'core:index' %}{% endblock nav_inicio %}
{% block nav_acerca_de %}{% url 'core:acerca_de' %}{% endblock nav_acerca_de %}
{% block nav_contactanos %}#{% endblock nav_contactanos %}
{% block content %}
    <div class="container mt-3 bg-dark">
        <form class="row g-3" method="POST" action="">
        {% csrf_token %}
            <div class="col-md-6">
                <label for="validationDefault01" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="validationDefault01" placeholder="nombre/s" name= "nombre"required>
            </div>
            <div class="col-md-6">
                <label for="validationDefault02" class="form-label">Apellido</label>
                <input type="text" class="form-control" id="validationDefault02" placeholder="apellido/s" name="apellido" required>
            </div>
            <div class="col-md-6">
                <label for="validationDefault03" class="form-label">Domicilio</label>
                <input type="text" class="form-control" id="validationDefault03" placeholder="barrio; direccion" name="domicilio" required>
            </div>
            <div class="col-md-6">
                <label for="validationDefault03" class="form-label">Ciudad</label>
                <input type="text" class="form-control" id="validationDefault03" placeholder="ciudad de residencia" name="ciudad" required>
            </div>
            <div class="col-md-6">
                <label for="validationDefault03" class="form-label">País</label>
                <input type="text" class="form-control" id="validationDefault03" placeholder="Pais de residencia" name="pais" required>
            </div>
            <div class="col-md-3">
                <label for="validationDefault05" class="form-label">CP</label>
                <input type="text" class="form-control" id="validationDefault05" placeholder="codigo postal" name="codigo_postal" required>
            </div>
            <div class="col-md-6">
                <label for="validationDefault06" class="form-label">Email</label>
                <div class="input-group">
                    <span class="input-group-text" id="inputGroupPrepend2">@</span>
                    <input type="email" class="form-control" id="validationDefault06" placeholder="ejemplo@gmail.com" aria-describedby="inputGroupPrepend2" name="email" required>
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationDefault07" class="form-label">Celular</label>
                <input type="number" class="form-control" id="validationDefault07" placeholder="numero de celular" pattern="[0-9]+" name="num_telefono" required  >
            </div>
            <div class="mb-3">
                <label for="validationDefault08" class="form-label">Mensaje</label>
                <textarea class="form-control" id="validationDefault08" rows="3" name="msj" required></textarea>
            </div>
            <div class="col-12 p-3">
                <button class="btn btn-primary" type="submit">Enviar</button>
            </div>
        </form>
{% endblock content %}