sin_miedo_al_exito/core/urls.py
from django.urls import path
from . import views

app_name="core"

urlpatterns = [
    path("", views.index.as_view(), name='index'),
    path("acerca_de/", views.acerca_de.as_view(), name='acerca_de'),
    path("raul/", views.raul.as_view(), name='portafolio_raul'),
    path("martin/", views.martin.as_view(), name='portafolio_martin'),
    path("contactanos/", views.contactanos.as_view(), name='contactanos'),
]

sin_miedo_al_exito/cursos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name="cursos"

urlpatterns = [
    path('listado_de_cursos/',views.cursoListView.as_view(), name='listado_cursos' ),
    path('<int:pk>/', views.cursoDetailView.as_view(), name='curso_detalle'),
    path('crear_curso/', login_required(views.cursoCreate.as_view()), name='curso_crear'),
    path('actualizar_curso/<int:pk>/', login_required(views.cursoUpdate.as_view()), name='actualizar_curso'),
    path('borrar_curso/<int:pk>/', login_required(views.cursoDelete.as_view()), name='borrar_curso'),
]

sin_miedo_al_exito/sin_miedo_al_exito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace='core')),
    path('', include("cursos.urls", namespace='course')),
    path('', include("usuarios.urls", namespace='usuarios')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sin_miedo_al_exito/cursos/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class curso(models.Model):
    nombre=models.CharField(max_length=75, verbose_name="Nombre")
    desc_corta=models.TextField(verbose_name="Descripcion_Corta", max_length=400)
    desc_larga=models.TextField(verbose_name="Descripción_larga")
    imagen=models.ImageField(verbose_name="Imagen", upload_to="imagenes_curso")
    url_video=models.URLField(verbose_name="link_video" )
    url_documentacion=models.URLField(verbose_name="link_documentacion")
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('curso_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"
        ordering = ["created"]

    def __str__(self):
        return self.nombre

sin_miedo_al_exito/cursos/forms.py
from django import forms
from .models import curso

class cursoForm(forms.ModelForm):

    class Meta:
        model = curso
        fields = [
                    'nombre',
                    'desc_corta',
                    'desc_larga',
                    'imagen',
                    'url_video',
                    'url_documentacion'
                ]

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control','placeholder':'Título'}),
            'desc_corta': forms.Textarea(attrs={'class':'form-control','placeholder':'Descripcion corta'}),
            'desc_larga': forms.Textarea(attrs={'class':'form-control','placeholder':'Descripcion larga'}),
            'imagen': forms.FileInput(attrs={'class':'form-control','placeholder':'Imagen'}),
            'url_video': forms.URLInput(attrs={'class':'form-control','placeholder':'Link Video'}),
            'url_descripcion': forms.URLInput(attrs={'class':'form-control','placeholder':'Link Documentacion'})
        }

        labels = {
                    'nombre': 'Nombre',
                    'desc_corta': 'Descripción corta',
                    'desc_larga': 'Descripción larga',
                    'imagen': 'Imagen',
                    'url_video': 'Video',
                    'url_documentacion': 'Documentación'
            }

sin_miedo_al_exito/cursos/views.py
from django.shortcuts import render, get_object_or_404
from .models import curso
from django.views.generic.detail import DetailView
from django.db.models import Q
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from cursos.models import curso
from django.urls import reverse, reverse_lazy
from .forms import cursoForm
from django.core.paginator import Paginator
# Create your views here.
class cursoListView(ListView):

    def get(self, request, *args, **kwargs):
        busqueda = request.GET.get("buscar")
        cursos_lista = curso.objects.all()
        if busqueda:
            cursos_lista = curso.objects.filter(
                Q(nombre__icontains = busqueda)
            ).distinct()
        page_numero = request.GET.get('page')
        cursos_page = Paginator(cursos_lista, 3)
        cursos_lista = cursos_page.get_page(page_numero)
        context = {
            'curso_list': cursos_lista,
            'busqueda': busqueda,
        }
        return render(request, "cursos/curso_list.html", context)
    model = curso

class cursoDetailView(DetailView):
    def get(self, request, *args, **kwargs):
        curso_de = get_object_or_404(curso, pk=kwargs['pk'])
        context = {'curso': curso_de}
        return render(request, 'cursos/curso_detail.html', context)

    model = curso


class cursoCreate(CreateView):
    model = curso
    form_class = cursoForm
    success_url = reverse_lazy('cursos:listado_cursos')

class cursoUpdate(UpdateView):
    model = curso
    form_class = cursoForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('cursos:listado_cursos')+'?Actualizado'

class cursoDelete(DeleteView):
    model = curso
    def get_success_url(self):
        return reverse_lazy('cursos:listado_cursos')+'?Eliminado'    

sin_miedo_al_exito/cursos/templates/cursos/curso_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar Curso{% endblock title %}
{% block estilos %}{% static 'css/estilos.css' %}{% endblock estilos %}
{% block nav_inicio %}{% url 'core:index' %}{% endblock nav_inicio %}
{% block nav_acerca_de %}{% url 'core:acerca_de' %}{% endblock nav_acerca_de %}
{% block contactanos %}{% url 'core:contactanos' %}{% endblock contactanos %}
{% block content %}
    <div class="container">
        <div class="row mt-3 mb-5">
            <div class="col-md-9 mx-auto">
                <div class="alert alert-warning d-flex align-items-center" role="alert">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>
                    <div>
                        <h2>¿Quieres borrar "{{ object }}"?</h2>
                    </div>
                </div>
                <form action="" method="post">{% csrf_token %}
                    <div class="container">
                        <div class="row">
                            <div class="col-6">
                                <input type="submit" class="nav-link btn btn-one" value="Confirmar" />
                            </div>
                            <div class="col-6">
                                <a style="text-decoration: none;" href="{% url 'cursos:curso_detalle' curso.pk %}">
                                    <input type="button" class="nav-link btn btn-one" value="Cancelar">
                                </a>
                            </div>
                        </div>
                    </div>
                </form>      
            </div>
        </div>
    </div>
{% endblock %}

sin_miedo_al_exito/cursos/templates/cursos/curso_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{curso.nombre}}{%endblock title %}
{% block estilos %}{% static 'css/estilos.css' %}{% endblock estilos %}
{% block nav_inicio %}{% url 'core:index' %}{% endblock nav_inicio %}
{% block nav_acerca_de %}{% url 'core:acerca_de' %}{% endblock nav_acerca_de %}
{% block contactanos %}{% url 'core:contactanos' %}{% endblock contactanos %}
{% block content %}
    <div class="row accordion-body">
        <div class="col-12 col-lg-7">
            <h2 class="titulo_curso">{{curso.nombre}}</h2>
            <p class="descripcion_curso text-dark">{{curso.desc_larga}}</p>
        </div>
        <div class="col-12 col-lg-5 row">
            <img class="zoom" src="{{curso.imagen.url}}" alt="foto curso">
            <a target="_blank" class="enlace text-center" href="{{curso.url_video}}">
                <span class="align-middle">Enlace video sobre {{curso.nombre}}</span>
            </a>
            <a target="_blank" class="enlace text-center" href={{curso.url_documentacion}}>
                <span class="align-middle"> Enlace Documentacion sobre {{curso.nombre}}</span>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-2">
            <a class="nav-link btn btn-two" href="{% url 'cursos:actualizar_curso' curso.pk %}">Actualizar</a>
        </div>
        <div class="col-12 col-sm-2">
            <a class="nav-link btn btn-two" href="{% url 'cursos:borrar_curso' curso.pk %}">borrar</a>
        </div>
    </div>
    
{% endblock content %} 

sin_miedo_al_exito/cursos/templates/cursos/curso_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear Curso{% endblock title %}
{% block estilos %}{% static 'css/estilos.css' %}{% endblock estilos %}
{% block nav_inicio %}{% url 'core:index' %}{% endblock nav_inicio %}
{% block nav_acerca_de %}{% url 'core:acerca_de' %}{% endblock nav_acerca_de %}
{% block contactanos %}{% url 'core:contactanos' %}{% endblock contactanos %}
{% block content %}
    <div class="container">
        <div class="row mt-3 mb-5">
            <div class="col-md-9 mx-auto">
                <form action="" method="post" class="bg-dark p-3" enctype="multipart/form-data">{% csrf_token %}
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Título</label>
                        <input type="text" class="form-control" id="nombre" placeholder="Título" name="nombre">
                    </div>
                    <div class="mb-3">
                        <label for="descripcion_corta" class="form-label">Descripción Corta:</label>
                        <textarea id="descripcion_corta" class="form-control" rows="4" placeholder="Descripción corta del tema." name="desc_corta"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="descripcion_larga" class="form-label">Descripción Larga</label>
                        <textarea id="descripcion_larga" class="form-control" rows="7" placeholder="Descripción larga del tema." name="desc_larga"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="imagen" class="form-label">Imagen:</label>
                        <input type="file" accept="image/*" id="imagen" placeholder="Imagen" name="imagen">
                    </div>
                    <div class="mb-3">
                        <label for="url_video" class="form-label">Video sobre el curso:</label>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon3">https://example.com/users/</span>
                            <input type="url" class="form-control" id="url_video" aria-describedby="basic-addon3" placeholder="Link video" name="url_video">
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="url_documentacion" class="form-label">Documentacion sobre el curso:</label>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon3">https://example.com/users/</span>
                            <input type="url" class="form-control" id="url_documentacion" aria-describedby="basic-addon3" placeholder="Link Documentacion" name="url_documentacion">
                        </div>
                    </div>
                    <div class="text-center p-2">
                        <input type="submit" class="nav-link btn btn-one" value="crear"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

sin_miedo_al_exito/cursos/templates/cursos/curso_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Listado de Cursos{% endblock title %}
{% block estilos %}{% static 'css/estilos.css' %}{% endblock estilos %}
{% block nav_inicio %}{% url 'core:index' %}{% endblock nav_inicio %}
{% block nav_acerca_de %}{% url 'core:acerca_de' %}{% endblock nav_acerca_de %}
{% block contactanos %}{% url 'core:contactanos' %}{% endblock contactanos %}
{% block busqueda %}
<div class="container-fluid">
    <form class="d-flex" method="GET">
        <input class="form-control buscador" type="search" placeholder="buscar curso" aria-label="Search" name="buscar">
        <button class="btn btn-one nav-link" type="submit"><font size="5">Buscar</font></button>
    </form>
</div>
{% endblock busqueda %}
{% block content %}

<!--raul-->
{% include 'cursos/includes/mensajes_alertas.html' %}
<!--fin-->
    {% if user.username  %}
        <div class="contenedor text-center text-light">
            <h2 class="titulo_curso">Bienvenido {{ user.username | upper }} <br> ¿Listo para aprender?</h2>
        </div>
    {% endif %}

    <div class="text-center">                               
        <a class="nav-link btn btn-one" href="{% url 'cursos:curso_crear' %}"><font size="5">Crear Nuevo Curso</font></a>
    </div>
    <div class="container">
    {% if curso_list %}
            {% for tema_curso in curso_list %}
            <div class="row contenedor">
                <div class="col-12 col-lg-7 contenedor_detalle p-2">
                    <a class="nav-link btn btn-one bg-dark" href="{% url 'cursos:curso_detalle' tema_curso.pk %}">
                        <h2 class="titulo_curso">{{tema_curso.nombre}}</h2>
                    </a>
                    <p class="text-dark desc_corta">{{tema_curso.desc_corta}}</p>
                </div>
                <div class="col-12 col-lg-5 row">
                    <img class="zoom w-75 mx-auto d-block" src="{{tema_curso.imagen.url}}" alt="foto curso">
                </div>
            </div>
            {% endfor %}
    {% else %}
        <h2 class="mensaje_error">No hay elementos que coincidan con "{{busqueda}}"</h2>
    {% endif %}
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end p-3">
        {% if curso_list.has_previous %}
            <li class="page-item">
                <a class="page-link bg-dark link-info" href= "?page={{ curso_list.previous_page_number }}"><font size="4">Anterior</font></a>
            </li>
        {% endif %}
        {% for pagina in curso_list.paginator.page_range %}
            {% if pagina == page_obj.number %}
                <li class="page-item">
                    <a class="page-link bg-dark link-info" href="#"><font size="4">{{ pagina }}</font></a>
                </li>                
            {% else %}
                <li class="page-item">
                    <a class="page-link bg-dark link-info" href="?page={{ pagina }}"><font size="4">{{ pagina }}</font></a>
                </li>
            {% endif %}
        {% endfor %}
        {% if curso_list.has_next %}
            <li class="page-item">
                <a class="page-link bg-dark link-info" href="?page={{ curso_list.next_page_number }}"><font size="4">Siguiente</font></a>
            </li>
        {% endif %}
        </ul>
    </nav>
{% endblock content %}

sin_miedo_al_exito/cursos/templates/cursos/curso_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar Curso{% endblock title %}
{% block estilos %}{% static 'css/estilos.css' %}{% endblock estilos %}
{% block nav_inicio %}{% url 'core:index' %}{% endblock nav_inicio %}
{% block nav_acerca_de %}{% url 'core:acerca_de' %}{% endblock nav_acerca_de %}
{% block contactanos %}{% url 'core:contactanos' %}{% endblock contactanos %}
{% block content %}
    <div class="container">
        <div class="row mt-3 mb-5">
            <div class="col-md-9 mx-auto">
                <form action="" method="post" class="bg-dark p-3" enctype="multipart/form-data">{% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center">
                        <input type="submit" class="nav-link btn btn-one" value="Actualizar" />
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}